### PR TITLE
enable access to SequenceNumber

### PR DESCRIPTION
**Pull request by ChemiKyle**
Partially addresses issue #37 
SequenceNumber is accessible and works as expected

Scraping in subject ID is a little more complicated; it _is_ returned from OnCore under the key `id`, but the module is coercing all variables (hardcoded in `config.json`) to PascalCase causing `id` to be mapped to `Id`.

We could attempt to map it elsewhere, get rid of conversion PascalCase, or ignore it.

### CODE REVIEW

**Comment by pbchase** [comment]
I can map and use the Sequence Number data as I had hoped, but the `View OnCore Data` button now shows no data. It's supposed to show the OnCore data for the mapped fields

**Comment by ChemiKyle** [comment]
This is the offending line:

https://github.com/ctsit/redcap_oncore_client/blob/47aece2801637d10763c5345d84d546c75e8541f/ExternalModule.php#L301

The order of the data in `config.json` matters, the index is hardcoded in for the creation of the array for labels.

I decided to put the new attributes higher in the file since they fit more in preceding subject name. It's chance I did not break this before. I can just move them lower, but this should probably be refactored in the future.

**Comment by pbchase** [comment]
@ChemiKyle, this is better, but it is still not right in some cases. When I `View OnCore Data` I now get a dialog box with data.  I see the fields PrimaryIdentifier, FirstName, LastName, and BirthDate. SequenceNumber is configured to write into record_id. When I try to Pull OnCore Subjects I get

```
 Success! Your changes have been saved.
 Success! Your changes have been saved.
 An issue prevented pull from acting as expected
```

No records will import. This is in a project with zero imported records. it happens this way with autonumbering turned on or off. 

As far as I can tell, the problem is the sequence number field in the protocol I am testing with is null. When I switched to a protocol with non-null sequence numbers, OCR20388, the software worked fine.  Related to this, the sequence number is not a required field in OnCore. Yet some projects use it and maintain it as a unique number. 

Could you add a test that whatever field is mapped to the record_id is not null? Provide an alert message along the lines of "Record `<OnCore_PrimaryIdentifier>` could not be loaded because  `<name_of_mapped_oncore_field>` is blank".

**Comment by ChemiKyle** [comment]
@pbchase I addressed this in 77f0ae2

While testing, I discovered #39 applies to `SequenceNumber` as well

**Comment by pbchase** [comment]
@ChemiKyle said the null sequence numbers exist in the protocol OCR17881.

**Pull request merged**
